config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'admin', to: 'products#index'
  resources :home do
    member do
      get :register
    end
  end

  resources :orders do
    member do
      get :list
      get :finish
    end
  end
  resources :visitors
  resources :scheduled_products do
    member do 
      get :list
    end
  end
  resources :schedules
  resources :products
  resources :ordered_products do
    member do 
      get :choose_schedule
      get :list
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
	belongs_to :order
	belongs_to :scheduled_product
end

app/controllers/ordered_products_controller.rb
class OrderedProductsController < ApplicationController
  before_action :set_ordered_product, only: %i[ show edit update destroy ]
  
  def choose_schedule
    @ordered_product = OrderedProduct.new
    @schedule = Schedule.where("dateopen < ? AND dateclose > ?", DateTime.now, DateTime.now).order(dateopen: :asc)

    @order = Order.where("key = ?", params[:id])
    
    @order.each do |order|
      @id = order.visitor_id
      @visitor = Visitor.find(@id)
    end
  end

  def list
    @ordered_product = OrderedProduct.new
    @schedule = Schedule.find(params[:id])
    @order = Order.where("key = ?", params[:key])
    @order.each do |order|
      @id = order.id
      @visitorid = order.visitor_id
      @visitor = Visitor.find(@visitorid)
      @key = order.key
    end

     @choice = OrderedProduct.where("order_id = ?", @id)
  end

  # GET /ordered_products or /ordered_products.json
  def index
    @ordered_products = OrderedProduct.all.order(id: :desc)
  end

  # GET /ordered_products/1 or /ordered_products/1.json
  def show
  end

  # GET /ordered_products/new
  def new
    @ordered_product = OrderedProduct.new
  end

  # GET /ordered_products/1/edit
  def edit
  end

  # POST /ordered_products or /ordered_products.json
  def create
    @ordered_product = OrderedProduct.new(ordered_product_params)

    @ordered_product.price = @ordered_product.scheduled_product.product.price
    @ordered_product.total = @ordered_product.quantity * @ordered_product.scheduled_product.product.price
    @ordered_product.profit = @ordered_product.quantity * (@ordered_product.scheduled_product.product.price - @ordered_product.scheduled_product.product.cost)

    respond_to do |format|
      if @ordered_product.save

        @key = @ordered_product.order.key
        @id = @ordered_product.scheduled_product.schedule.id

        format.html { redirect_to list_ordered_product_path(@id, :key => @key), notice: "Ordered product was successfully created." }
        format.json { render :show, status: :created, location: @ordered_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordered_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordered_products/1 or /ordered_products/1.json
  def update
    respond_to do |format|
      if @ordered_product.update(ordered_product_params)
        format.html { redirect_to @ordered_product, notice: "Ordered product was successfully updated." }
        format.json { render :show, status: :ok, location: @ordered_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordered_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordered_products/1 or /ordered_products/1.json
  def destroy
    @key = @ordered_product.order.key
    @id = @ordered_product.scheduled_product.schedule.id

    @ordered_product.destroy
    respond_to do |format|
      format.html { redirect_to list_ordered_product_path(@id, :key => @key), notice: "Ordered product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordered_product
      @ordered_product = OrderedProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ordered_product_params
      params.require(:ordered_product).permit(:quantity, :price, :profit, :total, :description, :order_id, :scheduled_product_id)
    end
end

app/helpers/ordered_products_helper.rb
module OrderedProductsHelper
end

app/views/ordered_products/_form.html.erb
<%= form_with(model: ordered_product) do |form| %>
  <% if ordered_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordered_product.errors.count, "error") %> prohibited this ordered_product from being saved:</h2>

      <ul>
        <% ordered_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.number_field :price, type:'hidden', value:'0' %>
  </div>

  <div class="field">
    <%= form.number_field :profit, type:'hidden', value:'0' %>
  </div>

  <div class="field">
    <%= form.number_field :total, type:'hidden', value:'0' %>
  </div>

  <div class="field">
    <%= form.number_field :order_id, type:'hidden', value:@id %>
  </div>

  <div class="form-group">
    <% if @schedule.present? %>
    <%= form.collection_select :scheduled_product_id, ScheduledProduct.where("schedule_id = ?", @schedule.id).order(:id), :id, :name_with_price, {}, {class:"form-control", style:'text-transform:capitalize;'} %>
    <% else %>
    <%= form.collection_select :scheduled_product_id, ScheduledProduct.all.order(:id), :id, :name_with_price, {}, {class:"form-control", style:'text-transform:capitalize;'} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.number_field :quantity, value:1, class:"form-control", autocomplete:"off", required:"true", min:"1" %>
  </div>

  <div class="form-group">
    <%= form.text_area:description, size: "30x3", class:"form-control", placeholder:"Deskripsi pesanan, ex: pedas, extra kuah, etc.." %>
  </div>

  <div class="actions">
    <%= form.submit "Tambahkan", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/ordered_products/choose_schedule.html.erb
<br>
<h4><strong>Klik Jadwal yang Diinginkan</strong></h4>

<div>
	<% @schedule.each do |schedule| %>
	<hr>
	<div>
		<%= link_to schedule.datedelivery.to_formatted_s(:rfc822) , list_ordered_product_path(schedule.id, :key => params[:id]), class:'btn btn-primary' %>
	</div>
	<br>
	<div class='container'>
		<table class="table table-striped">
			<tbody>
				<% @scheduled_product = ScheduledProduct.where("schedule_id = ?", schedule.id) %>
				<% @scheduled_product.each do |schedule_product|%>
				<tr>
					<td style="width: 20%"><%= image_tag(schedule_product.product.link, :alt => "menuprofile", :class => "itemavatar") %></td>
					<td><h3 style="text-transform: capitalize;"><strong><%= schedule_product.product.name %></strong></h3>
	        		<p><%= number_to_currency(schedule_product.product.price, unit: "Rp ") %></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<% end %>
</div>

<br>
<br>

app/views/ordered_products/edit.html.erb
<h1>Editing Ordered Product</h1>

<%= render 'form', ordered_product: @ordered_product %>

<%= link_to 'Show', @ordered_product %> |
<%= link_to 'Back', ordered_products_path %>

app/views/ordered_products/index.html.erb
<h1>Ordered Products</h1>
<br>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Scheduled Product</th>
      <th>Order ID</th>
      <th>Price</th>
      <th>Profit</th>
      <th>Total</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordered_products.each do |ordered_product| %>
      <tr>
        <td><%= ordered_product.scheduled_product_id %></td>
        <td><%= ordered_product.order_id %></td>
        <td><%= ordered_product.price %></td>
        <td><%= ordered_product.profit %></td>
        <td><%= ordered_product.total %></td>
        <td><%= ordered_product.description %></td>
        <td><%= link_to 'Show', ordered_product %></td>
        <td><%= link_to 'Edit', edit_ordered_product_path(ordered_product) %></td>
        <td><%= link_to 'Destroy', ordered_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Ordered Product', new_ordered_product_path, class:'btn btn-primary' %>

app/views/ordered_products/list.html.erb
<div style='text-transform: capitalize; text-align: right'>
	<h3><strong><%= @visitor.name %></strong></h3>
	<h4><%= @visitor.address %> - <%= @visitor.phone %></h4>
	<h4><strong><%= @schedule.datedelivery.to_formatted_s(:rfc822) %></strong></h4>
</div>
<hr>
<div class="row">
	<div class="col-md-4" style="margin-bottom: 30px;">
		<%= render 'form', ordered_product: @ordered_product %>
	</div>
	<div class="col-md-8">
		<h3>Daftar Pesanan</h3>
		<div class="table-responsive">
			<table class='table table-striped'>
			  <thead>
			    <tr>
			      <th>Name</th>
			      <th>Quantity</th>
			      <th>Total</th>
			      <th>Description</th>
			      <th style="width:10%"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @choice.each do |choice| %>
			      <tr>
			        <td style='text-transform:capitalize;'><%= choice.scheduled_product.product.name %></td>
			        <td><%= choice.quantity %></td>
			        <td><%= choice.total %></td>
			        <td><%= choice.description %></td>
			        <td><%= link_to 'X', choice, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
			</div>
	</div>
</div>

<div>
	<%= link_to "Selesaikan Pesanan" , finish_order_path(key: @key), class:'btn btn-success btn-block' %>
</div>

app/views/ordered_products/new.html.erb
<h1>New Ordered Product</h1>

<%= render 'form', ordered_product: @ordered_product %>

<%= link_to 'Back', ordered_products_path %>

app/views/ordered_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @ordered_product.price %>
</p>

<p>
  <strong>Profit:</strong>
  <%= @ordered_product.profit %>
</p>

<p>
  <strong>Total:</strong>
  <%= @ordered_product.total %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ordered_product.description %>
</p>

<%= link_to 'Edit', edit_ordered_product_path(@ordered_product) %> |
<%= link_to 'Back', ordered_products_path %>