config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'admin', to: 'products#index'
  resources :home do
    member do
      get :register
    end
  end

  resources :orders do
    member do
      get :list
      get :finish
    end
  end
  resources :visitors
  resources :scheduled_products do
    member do 
      get :list
    end
  end
  resources :schedules
  resources :products
  resources :ordered_products do
    member do 
      get :choose_schedule
      get :list
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	has_many :scheduled_product
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /schedules or /schedules.json
  def index
    @futureschedules = Schedule.where("datedelivery >= ?", DateTime.now).order(dateopen: :asc)

    @pastschedules = Schedule.where("datedelivery <= ?", DateTime.now).order(dateopen: :desc)
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to list_scheduled_product_path(@schedule), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedules_url, notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:dateopen, :dateclose, :datedelivery)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="form-group">
    <%= form.label :"Preoder Open Date" %>
    <br>
    <%= form.date_field :dateopen, class:'form-control', required:'true' %>
  </div>

  <div class="form-group">
    <%= form.label :"Preoder Close Date" %>
    <br>
    <%= form.date_field :dateclose, class:'form-control', required:'true' %>
  </div>

  <div class="form-group">
    <%= form.label :"Delivery Date"%>
    <br>
    <%= form.date_field :datedelivery, class:'form-control', required:'true' %>
  </div>


  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<br>
<%= link_to 'Back', schedules_path, class:'btn btn-secondary' %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<br>
<h3>Future Schedules</h3>

<br>
<div><%= link_to 'New Schedule', new_schedule_path, class:'btn btn-primary' %>
</div>
<br>
<div class="table-responsive">
<table class='table table-striped'>
  <thead>
    <tr>
      <th>No.</th>
      <th>Dateopen</th>
      <th>Dateclose</th>
      <th>Delivery</th>
      <th colspan="4" style="width:10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @counter = 1 %>
    <% @futureschedules.each do |schedule| %>
      <tr>
        <td><%= @counter %></td>
        <td><%= schedule.dateopen.to_formatted_s(:rfc822) %></td>
        <td><%= schedule.dateclose.to_formatted_s(:rfc822) %></td>
        <td><%= schedule.datedelivery.to_formatted_s(:rfc822) %></td>
        <td><%= link_to 'Order List', list_order_path(schedule), class:'btn btn-primary' %></td>
        <td><%= link_to 'Product List', list_scheduled_product_path(schedule), class:'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule), class:'btn btn-secondary' %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
      <% @counter += 1 %>
    <% end %>
  </tbody>
</table>
</div>

<br>

<h3>Past Schedules</h3>

<div class="table-responsive">
<table class='table table-striped'>
  <thead>
    <tr>
      <th>No.</th>
      <th>Dateopen</th>
      <th>Dateclose</th>
      <th colspan="3" style="width:10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @counter = 1 %>
    <% @pastschedules.each do |schedule| %>
      <tr>
        <td><%= @counter %></td>
        <td><%= schedule.dateopen.to_formatted_s(:rfc822) %></td>
        <td><%= schedule.dateclose.to_formatted_s(:rfc822) %></td>
        <td><%= link_to 'List', list_scheduled_product_path(schedule), class:'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule), class:'btn btn-secondary' %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
      <% @counter += 1 %>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<br>
<%= link_to 'Back', schedules_path, class:'btn btn-secondary' %>

app/views/schedules/show.html.erb
<p>
  <strong>Dateopen:</strong>
  <%= @schedule.dateopen %>
</p>

<p>
  <strong>Dateclose:</strong>
  <%= @schedule.dateclose %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>