config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'admin', to: 'products#index'
  resources :home do
    member do
      get :register
    end
  end

  resources :orders do
    member do
      get :list
      get :finish
    end
  end
  resources :visitors
  resources :scheduled_products do
    member do 
      get :list
    end
  end
  resources :schedules
  resources :products
  resources :ordered_products do
    member do 
      get :choose_schedule
      get :list
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @schedules = Schedule.where("dateopen <= ? AND dateclose >= ?", DateTime.now, DateTime.now).order(dateopen: :asc).limit(1)

    @dateopen = "No Preorder"
    @id = -1;
    @schedules.each do |schedule| 
      @dateopen = schedule.datedelivery.to_formatted_s(:rfc822)
      @id = schedule.id
    end

    @scheduled_product = ScheduledProduct.where("schedule_id = ?", @id)
  end

  def register
    @visitor = Visitor.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "Poppys Kitchen", root_path, class:'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Product', products_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Schedule', schedules_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Order', orders_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Visitor', visitors_path, class:'nav-link' %>
      </li>

      <% if user_signed_in? %>
      
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>

      <% else %>

      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
      </li>
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<div style="background-color: black">
	<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
	  <div class="carousel-inner">
	    <div class="carousel-item active">
	    	<div class="d-flex align-items-cover justify-content-center min-vh-100">
          <%= image_tag("hero.jpg", :alt => "hero", :class => "d-block w-100", :style => "object-fit: cover;") %>
		    	<div class="header-text">
						<div class="col-md-8 col-xs-8 w3-container w3-animate-right">
							<div class="d-sm-block d-md-none" style="height:50px; width: 100%;"></div>
							<h2 class="d-md-none d-sm-block" style="font-size:50px;">
								<span>Selamat Datang di <strong>Poppy's Kitchen</strong></span>
							</h2>

							<h2 class="d-none d-md-inline-block" style="font-size:6vw;">
								<span>Selamat Datang di <strong>Poppy's Kitchen</strong></span>
							</h2>

							<br>
							<h3 style="font-size:4vw;">
								Lihat menu pre-order terdekat
							</h3>
							<%= link_to @dateopen , list_scheduled_product_path(@id), class:'btn btn-info btn-lg', "data-toggle" => "modal", "data-target" => "#menuModal" %>

							<br>
							<br>
							<h3 style="font-size:4vw;">
								Mau pesanan khusus?
							</h3>
							<a href="https://wa.me/628113505920?text=Saya%20tertarik%20dengan%20masakan%20yang%20anda%20jual" target="_blank"><button class='btn btn-success'><i class="fa fa-whatsapp"></i> Klik dan hubungi lewat Whatsapp</button></a>
						</div><!-- /header-text -->
					</div>
        </div>
			</div>
	  </div>
	</div>

	<br>
	<div class="container w3-animate-opacity">
		<div class="row">
			<div class="col-md-7">
				<strong><h2 style="color: white">Siapa yang suka dengan Chinese Food?</h2></strong>
				<h5 style="color: #949494; margin-bottom: 30px;">
					Dengan menu andalan Mie Ayam, yang disajikan dengan tekstur yang kenyal dan kuah yang gurih. Ditambahkan juga dengan suwiran daging ayam, bakso, dan irisan mentimun. Ada pilihan pelengkap mie ayam selain bakso yang bisa kamu pilih yaitu pangsit rebus.
				</h5>
			</div>
			<div class="col-md-5">
				<%= image_tag("profile.jpg", :alt => "hero", :class => "d-block w-100") %>
			</div>
			
		</div>
		<br>
		<div class="row">
			<div class="col-md-12">
				<br>
				<center>
					<strong><h2 style="color: white">Jika anda mempunyai pertanyaan?</h2></strong>
					<h3 style="color: #949494">Bicara langsung dengan saya</h3>
					<br>
					<a href="https://wa.me/628113505920?text=Saya%20tertarik%20dengan%20masakan%20yang%20anda%20jual" target="_blank"><button class='btn btn-success'><i class="fa fa-whatsapp"></i> Klik dan hubungi lewat Whatsapp</button></a>
				</center>
			</div>
		</div>
	</div>

	<div style="margin-top: 45px;">
		<!-- Footer -->
		<footer class="page-footer font-small blue">

		  <!-- Copyright -->
		  <div class="footer-copyright text-center py-3" style="color:grey">© 2021 Copyright:
		    <a href="https://instagram.com/dhanihimawan"  target="_blank"> @dhanihimawan</a>
		  </div>
		  <!-- Copyright -->

		</footer>
		<!-- Footer -->
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="menuModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><strong>Daftar Menu</strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @scheduled_product.each do |scheduledproduct| %>
        	<div class='container'>
        		<div class="row">
	      			<div class='col-6'>
	        			<%= image_tag(scheduledproduct.product.link, :alt => "menuprofile", :class => "d-block w-100") %>
	        		</div>
	        		<div class='col-6'>
		       			<h3 style="text-transform: capitalize;"><strong><%= scheduledproduct.product.name %></strong></h3>
	        			<p><%= number_to_currency(scheduledproduct.product.price, unit: "Rp ") %></p>
	        		</div>
	        	</div>
        	</div>
        	<br>
	    <% end %>
      </div>
      <div class="modal-footer">
      	<% if @id!=-1 %>
      	<%= link_to 'Ikut Preorder', register_home_path(@id), class:'btn btn-primary' %>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/page1.html.erb
<br>

<h3>Masukkan Data Diri Anda</h3>
<br>

<%= render 'visitors/form', visitor: @visitor %>

app/views/home/register.html.erb
<br>

<h3>Masukkan Data Diri Anda</h3>
<br>

<%= render 'visitors/form', visitor: @visitor %>

app/views/home/visitor.html.erb
<br>

<h3>Masukkan Data Diri Anda</h3>
<br>

<%= render 'visitors/form', visitor: @visitor %>