config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'admin', to: 'products#index'
  resources :home do
    member do
      get :register
    end
  end

  resources :orders do
    member do
      get :list
      get :finish
    end
  end
  resources :visitors
  resources :scheduled_products do
    member do 
      get :list
    end
  end
  resources :schedules
  resources :products
  resources :ordered_products do
    member do 
      get :choose_schedule
      get :list
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/scheduled_product.rb
class ScheduledProduct < ApplicationRecord
	belongs_to :product
	belongs_to :schedule

	has_many :ordered_product

	def name_with_price
		"#{product.name} - #{product.price}"
	end
end

app/controllers/scheduled_products_controller.rb
class ScheduledProductsController < ApplicationController
  before_action :set_scheduled_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  #custom
  def list
    @schedules = Schedule.find(params[:id]);
    @existing_scheduled_products = ScheduledProduct.where(schedule_id: params[:id])
    @total = @existing_scheduled_products.count

    @scheduled_product = ScheduledProduct.new
  end

  # GET /scheduled_products or /scheduled_products.json
  def index
    @scheduled_products = ScheduledProduct.all
  end

  # GET /scheduled_products/1 or /scheduled_products/1.json
  def show
  end

  # GET /scheduled_products/new
  def new
    @scheduled_product = ScheduledProduct.new
  end

  # GET /scheduled_products/1/edit
  def edit
  end

  # POST /scheduled_products or /scheduled_products.json
  def create
    @scheduled_product = ScheduledProduct.new(scheduled_product_params)

    respond_to do |format|
      if @scheduled_product.save
        format.html { redirect_to list_scheduled_product_url(@scheduled_product.schedule_id), notice: "Scheduled product was successfully created." }
        format.json { render :show, status: :created, location: @scheduled_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scheduled_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_products/1 or /scheduled_products/1.json
  def update
    respond_to do |format|
      if @scheduled_product.update(scheduled_product_params)
        format.html { redirect_to list_scheduled_product_url(@scheduled_product.schedule_id), notice: "Scheduled product was successfully updated." }
        format.json { render :show, status: :ok, location: @scheduled_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scheduled_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_products/1 or /scheduled_products/1.json
  def destroy
    @scheduled_product.destroy
    respond_to do |format|
      format.html { redirect_to list_scheduled_product_url(@scheduled_product.schedule_id), notice: "Scheduled product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_product
      @scheduled_product = ScheduledProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scheduled_product_params
      params.require(:scheduled_product).permit(:product_id, :schedule_id)
    end
end

app/helpers/scheduled_products_helper.rb
module ScheduledProductsHelper
end

app/views/scheduled_products/_form.html.erb
<%= form_with(model: scheduled_product) do |form| %>
  <% if scheduled_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduled_product.errors.count, "error") %> prohibited this scheduled_product from being saved:</h2>

      <ul>
        <% scheduled_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :schedule_id, class:"form-control", value:params[:id], type:"hidden" %>

  <div class="field form-group">
    <%= form.collection_select :product_id, Product.order(:id), :id, :name, {}, {class:"form-control", style:'text-transform:capitalize;'} %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Product', class:'btn btn-primary' %>
  </div>
<% end %>

<br>

app/views/scheduled_products/edit.html.erb
<h1>Editing Scheduled Product</h1>

<%= render 'form', scheduled_product: @scheduled_product %>

<%= link_to 'Show', @scheduled_product %> |
<%= link_to 'Back', scheduled_products_path %>

app/views/scheduled_products/index.html.erb
<h1>Scheduled Products</h1>

<br>

<div class="table-responsive">
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Schedule ID</th>
      <th>Product Name</th>
      <th colspan="3" style="width:10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_products.each do |scheduled_product| %>
      <tr>
        <td><%= scheduled_product.schedule_id %></td>
        <td><%= scheduled_product.product.name %></td>
        <td><%= link_to 'Edit', edit_scheduled_product_path(scheduled_product), class:'btn btn-secondary' %></td>
        <td><%= link_to 'Destroy', scheduled_product, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/scheduled_products/list.html.erb
<br>

<h4>#<%= params[:id]%></h3>

<h5><strong>Date Open : <%= @schedules.dateopen.to_formatted_s(:rfc822) %></strong></h5>
<h5><strong>Date Close : <%= @schedules.dateclose.to_formatted_s(:rfc822) %></strong></h5>
<hr>

<center><h3>Product List in This Schedule (<%= @total %>)</h3></center>
<br>
<div class='row'>
  <div class='col-md-6'>
  <%= render 'form', scheduled_product: @scheduled_product %>
  </div>

  <div class='col-md-6'>
    <div class="table-responsive">
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Product Name</th>
            <th colspan="3" style="width:10%"></th>
          </tr>
        </thead>

        <tbody>
          <% @existing_scheduled_products.each do |scheduled_product| %>
            <tr>
              <td style='text-transform:capitalize;'><%= scheduled_product.product.name %></td>
              <td><%= link_to 'Destroy', scheduled_product, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<br>

<%= link_to 'Finish Adding Product', schedules_path, class:"btn btn-success btn-block" %>
<br>

app/views/scheduled_products/new.html.erb
<h1>New Scheduled Product</h1>

<%= render 'form', scheduled_product: @scheduled_product %>

<%= link_to 'Back', scheduled_products_path %>

app/views/scheduled_products/show.html.erb
<p>
  <strong>Product Name:</strong>
  <%= @scheduled_product.product.name %>
</p>

<%= link_to 'Edit', edit_scheduled_product_path(@scheduled_product) %> |
<%= link_to 'Back', scheduled_products_path %>